### ISSUE TITLE
Site trac.mcusim.org is down

### ISSUE THREAD

**Issue by hmf** [mcusim/MCUSim#27]
Why not track all issue here? While I am at it, you can also set-up discussion forum here. 

HTHs.

**Comment by dsalychev** [comment]
Hi. Well, initially I though that it's a good idea to be less dependent upon github. I wonder whether any discussion forum is needed or not at all :) Personally, I don't have time to continue this project at the moment.

**Comment by hmf** [comment]
Just a thought. Broken links do not attract people. More dependence on GtHub means less work for you. A quick response from your side may even help revive this project. Maybe a quick update to the README is enough. Thanks for the quick response.
